name: sistema_gestao_farmacia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  shared_preferences: ^2.0.8
  sqflite_common_ffi: ^2.0.0+4
  font_awesome_flutter: any
  #sqflite_web: ^1.0.0+1
  hive: ^2.0.4 # ou indexed_db: ^0.0.1
  path: ^1.9.0
  uuid: ^3.0.5
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.1.4
  sqflite_common_ffi_web: ^0.4.3+1

flutter:
  uses-material-design: true
